name: GitHub Actions CI

on: [push, pull_request]

jobs:
  cmake-build:
    name: CMake build (${{ matrix.image_name }})
    runs-on: ${{ matrix.image_name }}

    strategy:
      matrix:
        image_name: [macOS-latest, windows-2019, ubuntu-20.04]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: { submodules: recursive }
      - name: Configuring
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Building
        run: |
          cmake --build build --config Release
